variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy
  - pages

build_dgx:
  stage: build
  script:
    - module load python3 cuda/11.2
    - python3 -m pip install --upgrade cmake ninja wheel
    - python3 setup.py bdist_wheel
  tags:
    - x86_64
    - cuda11
    - shell
  artifacts:
    paths:
      - ./dist/*whl
    expire_in: 1 day

# build_power:
#   stage: build
#   script:
#     - python3 setup.py bdist_wheel
#   tags:
#     - ppc64le
#     - cuda10
#     - shell
#   artifacts:
#     paths:
#       - ./dist/*whl
#     expire_in: 1 day

deploy_dgx:
  stage: deploy
  script:
    - module load python3
    - python3 -m pip install keyring==12.0.0 keyrings.alt
    - python3 -m pip install twine==2.0.0 passlib
    - twine upload ./dist/*.whl  --repository-url="$GCC_PYPI_HOST"
  tags:
    - x86_64
    - cuda11
    - shell
  dependencies:
    - build_dgx
  only:
    - tags

# deploy_power:
#   stage: deploy
#   script:
#     - python3 -m pip install keyring==12.0.0 keyrings.alt
#     - python3 -m pip install twine==2.0.0 passlib
#     - python3 -m twine upload ./dist/*.whl --repository-url="$GCC_PYPI_HOST"
#   tags:
#     - ppc64le
#     - cuda10
#     - shell
#   dependencies:
#     - build_power
#   only:
#     - tags

pages:
  stage: pages
  script:
    - python3 -m pip install setuptools_scm
    - cd docs
    - make
    - cd ..
    - mkdir -p public
    - cd public
    - cp -r ../docs/build/* .
  tags:
    - x86_64
    - cuda11
    - shell
  artifacts:
    paths:
      - public
  only:
    - tags

build_docs:
  stage: build
  script:
    - python3 -m pip install setuptools_scm
    - cd docs
    - make
  tags:
    - x86_64
    - shell
  artifacts:
    paths:
      - ./docs/build/
    expire_in: 1 day

deploy_docs:
  stage: deploy
  image: ubuntu:latest
  script:
    - mkdir -p /var/www/html/ssc/ssc-raft-300/
    - rm -rf /var/www/html/ssc/ssc-raft-300/*
    - cp -r ./docs/build/* /var/www/html/ssc/ssc-raft-300/
  tags:
    - wiki
  dependencies:
    - build_docs
  # only:
  #   - tags
