variables:
  GIT_SUBMODULE_STRATEGY: recursive

stages:
  - build
  - deploy
  - pages

build_dgx:
  stage: build
  image: gccdockers/python-builder
  script:
    - python3 -m build --wheel
  tags:
    - x86_64
    - cuda11
    - docker
  artifacts:
    paths:
      - ./dist/*whl
    expire_in: 1 day

build_sdist:
  stage: build
  image: gccdockers/python-builder
  script:
    - python3 -m build --sdist
  tags:
    - x86_64
    - cuda11
    - docker
  artifacts:
    paths:
      - ./dist/*tar.gz
    expire_in: 1 day

deploy_sdist:
  stage: deploy
  image: gccdockers/python-builder
  script:
    - twine upload ./dist/*.tar.gz  --repository-url="$GCC_PYPI_HOST"
  tags:
    - x86_64
    - cuda11
    - docker
  dependencies:
    - build_sdist
  only:
    - tags

deploy_dgx:
  stage: deploy
  image: gccdockers/python-builder
  script:
    - twine upload ./dist/*.whl  --repository-url="$GCC_PYPI_HOST"
  tags:
    - x86_64
    - cuda11
    - docker
  dependencies:
    - build_dgx
  only:
    - tags

pages:
  stage: pages
  image: gccdockers/python-builder
  script:
    - python3 -m pip install myst-parser
    - cd docs
    - make
    - cd ..
    - mkdir -p public
    - cd public
    - cp -r ../docs/build/* .
  tags:
    - x86_64
    - cuda11
    - docker
  artifacts:
    paths:
      - public
  only:
    - tags

build_docs:
  stage: build
  image: gccdockers/python-builder
  script:
    - python3 -m pip install myst-parser
    - cd docs
    - make
  tags:
    - x86_64
    - docker
  artifacts:
    paths:
      - ./docs/build/
    expire_in: 1 day

deploy_docs:
  stage: deploy
  image: ubuntu:latest
  script:
    - mkdir -p /var/www/html/ssc/ssc-raft/
    - rm -rf /var/www/html/ssc/ssc-raft/*
    - cp -r ./docs/build/* /var/www/html/ssc/ssc-raft/
  tags:
    - wiki
  dependencies:
    - build_docs
  only:
    - tags
