#include <cuda.h>
#include <cufft.h>
#include <complex.h>
#include <tgmath.h> 
#include <cuda_runtime_api.h>
#include <stdio.h>
#include <string.h>
#include <helper_cuda.h>
#include <time.h>
#include <assert.h>
#include <iostream>
#include <fstream>
#include <cassert>
#include <vector>
#include <sstream>
#include <string>
#include <cublas.h>
#include <future>
#include <chrono>
#include <thread>
#include <omp.h>
#include <math.h>
#include "common/structs.h"
#include "filter.h"
#include "rebinning.h"
#include "tomoalignment.h"
#include "fbp.h"
#include "rings.h"
#include "flatdark.h"
