#pragma once
#include <cuda.h>
#include <cufft.h>
#include <complex.h>
#include <tgmath.h> 
#include <cuda_runtime_api.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <helper_cuda.h>
#include <time.h>
#include <assert.h>
#include <iostream>
#include <fstream>
#include <cassert>
#include <vector>
#include <sstream>
#include <string>
#include <cublas.h>
#include <future>
#include <chrono>
#include <thread>
#include <omp.h>
#include <math.h>
#include <cublas_v2.h>